language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO="django<2"
  - DJANGO="django<2.1"
  - DJANGO="django"

matrix:
  include:
    - python: 3.7
      dist: xenial
  exclude:
    - python: 3.7
      env: DJANGO="django<2"
    - python: 2.7
      env: DJANGO="django<2.1"
    - python: 2.7
      env: DJANGO="django"
    - python: 3.4
      env: DJANGO="django"

install:
  - pip install --pre $DJANGO
  - pip install pytest-django pytest-cov codecov

script:
  - pytest -v --cov

after_success:
  - codecov
