site_name: django-model-values
site_url: https://coady.github.io/django-model-values/
site_description: Taking the O out of ORM.
theme: material

repo_name: coady/django-model-values
repo_url: https://github.com/coady/django-model-values
edit_uri: ""

nav:
  - Introduction: index.md
  - Reference: reference.md
  - Example: example.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true

markdown_extensions:
  - admonition
  - footnotes
