name: release

on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: actions/checkout@v5
    - uses: astral-sh/setup-uv@v7
    - run: uv build
    - run: uv mkdocs gh-deploy --force
    - uses: pypa/gh-action-pypi-publish@release/v1
